sudo: required

services:
    - docker

#before_install:
#    - docker build -t infine/docker-react-test-app -f Dockerfile.dev .

#script:
#    - docker run infine/docker-react-test-app npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker"
    env: "Docker-env"
    bucket_name: "elasticbeanstalk-us-east-2-237705347618"
    bucket_path: "docker"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: "$AWS_SECRET_KEY"
